version: '3.8'
networks:
  django-service-bootstrap-net:
    name: django-service-bootstrap-net
services:
  db:
    image: postgres:10.7
    container_name: django-service-bootstrap-db
    environment:
      POSTGRES_USER: django_service_bootstrap
      POSTGRES_PASSWORD: django_service_bootstrap
      POSTGRES_DB: django_service_bootstrap_local
    ports:
      - "5544:5432"
    networks:
      - django-service-bootstrap-net
  redis:
    container_name: django-service-bootstrap-redis
    image: redis:4
    ports:
      - "6677:6379"
    command: redis-server --requirepass password
    networks:
      - django-service-bootstrap-net
